import json, uuid, datetime

def ts(hours_ago=0):
    dt = datetime.datetime.utcnow() - datetime.timedelta(hours=hours_ago)
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")

findings = [
    {"id": str(uuid.uuid4()), "rule_id": "OS-001", "rule_name": "Public blob storage container", "severity": "HIGH", "resource_id": "/subscriptions/SUB/resourceGroups/rg/providers/Microsoft.Storage/storageAccounts/testblob001", "resource_type": "Microsoft.Storage/storageAccounts", "resource_name": "testblob001", "resource_group": "openshield-rg", "subscription_id": "YOUR_SUBSCRIPTION_ID", "region": "uksouth", "description": "Storage container allows anonymous public read access.", "remediation": "Set publicAccess to None on the container.", "detected_at": ts(0), "tool_version": "0.1.0", "compliance": {"cis": "CIS 3.6", "nist": "SC-7", "iso27001": ""}},
    {"id": str(uuid.uuid4()), "rule_id": "OS-002", "rule_name": "Unencrypted managed disk", "severity": "CRITICAL", "resource_id": "/subscriptions/SUB/resourceGroups/rg/providers/Microsoft.Compute/disks/vm-disk-001", "resource_type": "Microsoft.Compute/disks", "resource_name": "vm-disk-001", "resource_group": "openshield-rg", "subscription_id": "YOUR_SUBSCRIPTION_ID", "region": "uksouth", "description": "Managed disk is not encrypted.", "remediation": "Enable disk encryption.", "detected_at": ts(0), "tool_version": "0.1.0", "compliance": {"cis": "CIS 7.2", "nist": "SC-28", "iso27001": ""}},
    {"id": str(uuid.uuid4()), "rule_id": "OS-003", "rule_name": "NSG allows RDP from internet", "severity": "HIGH", "resource_id": "/subscriptions/SUB/resourceGroups/rg/providers/Microsoft.Network/networkSecurityGroups/nsg-rdp", "resource_type": "Microsoft.Network/networkSecurityGroups", "resource_name": "nsg-open-rdp", "resource_group": "openshield-rg", "subscription_id": "YOUR_SUBSCRIPTION_ID", "region": "uksouth", "description": "NSG allows RDP from 0.0.0.0/0.", "remediation": "Restrict RDP to corporate IP.", "detected_at": ts(0), "tool_version": "0.1.0", "compliance": {"cis": "CIS 6.1", "nist": "SC-7", "iso27001": ""}},
    {"id": str(uuid.uuid4()), "rule_id": "OS-004", "rule_name": "NSG allows SSH from internet", "severity": "HIGH", "resource_id": "/subscriptions/SUB/resourceGroups/rg/providers/Microsoft.Network/networkSecurityGroups/nsg-ssh", "resource_type": "Microsoft.Network/networkSecurityGroups", "resource_name": "nsg-open-ssh", "resource_group": "openshield-rg", "subscription_id": "YOUR_SUBSCRIPTION_ID", "region": "uksouth", "description": "NSG allows SSH from 0.0.0.0/0.", "remediation": "Restrict SSH to corporate IP.", "detected_at": ts(0), "tool_version": "0.1.0", "compliance": {"cis": "CIS 6.2", "nist": "SC-7", "iso27001": ""}},
    {"id": str(uuid.uuid4()), "rule_id": "OS-005", "rule_name": "Key Vault purge protection disabled", "severity": "HIGH", "resource_id": "/subscriptions/SUB/resourceGroups/rg/providers/Microsoft.KeyVault/vaults/kv-nopurge", "resource_type": "Microsoft.KeyVault/vaults", "resource_name": "kv-nopurge", "resource_group": "openshield-rg", "subscription_id": "YOUR_SUBSCRIPTION_ID", "region": "uksouth", "description": "Key Vault purge protection is disabled.", "remediation": "Enable purge protection.", "detected_at": ts(0), "tool_version": "0.1.0", "compliance": {"cis": "CIS 8.4", "nist": "SC-28", "iso27001": ""}},
    {"id": str(uuid.uuid4()), "rule_id": "OS-006", "rule_name": "SQL Server TDE disabled", "severity": "HIGH", "resource_id": "/subscriptions/SUB/resourceGroups/rg/providers/Microsoft.Sql/servers/sql-no-tde", "resource_type": "Microsoft.Sql/servers", "resource_name": "sql-no-tde", "resource_group": "openshield-rg", "subscription_id": "YOUR_SUBSCRIPTION_ID", "region": "uksouth", "description": "SQL TDE disabled.", "remediation": "Enable TDE.", "detected_at": ts(0), "tool_version": "0.1.0", "compliance": {"cis": "CIS 4.1", "nist": "SC-28", "iso27001": ""}},
    {"id": str(uuid.uuid4()), "rule_id": "OS-007", "rule_name": "App Service HTTP not disabled", "severity": "HIGH", "resource_id": "/subscriptions/SUB/resourceGroups/rg/providers/Microsoft.Web/sites/webapp-http", "resource_type": "Microsoft.Web/sites", "resource_name": "webapp-http", "resource_group": "openshield-rg", "subscription_id": "YOUR_SUBSCRIPTION_ID", "region": "uksouth", "description": "App Service allows HTTP.", "remediation": "Enable HTTPS only.", "detected_at": ts(0), "tool_version": "0.1.0", "compliance": {"cis": "CIS 9.2", "nist": "SC-8", "iso27001": ""}},
    {"id": str(uuid.uuid4()), "rule_id": "OS-008", "rule_name": "Container registry admin enabled", "severity": "HIGH", "resource_id": "/subscriptions/SUB/resourceGroups/rg/providers/Microsoft.ContainerRegistry/registries/acr-admin", "resource_type": "Microsoft.ContainerRegistry/registries", "resource_name": "acr-admin", "resource_group": "openshield-rg", "subscription_id": "YOUR_SUBSCRIPTION_ID", "region": "uksouth", "description": "ACR admin account enabled.", "remediation": "Disable admin account.", "detected_at": ts(0), "tool_version": "0.1.0", "compliance": {"cis": "CIS 5.6", "nist": "AC-6", "iso27001": ""}},
    {"id": str(uuid.uuid4()), "rule_id": "OS-009", "rule_name": "Overprivileged service principal", "severity": "HIGH", "resource_id": "/subscriptions/SUB/resourceGroups/rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/sp-contributor", "resource_type": "Microsoft.ManagedIdentity/userAssignedIdentities", "resource_name": "sp-contributor", "resource_group": "openshield-rg", "subscription_id": "YOUR_SUBSCRIPTION_ID", "region": "uksouth", "description": "SP has Contributor at subscription scope.", "remediation": "Scope to minimum resource group.", "detected_at": ts(0), "tool_version": "0.1.0", "compliance": {"cis": "CIS 1.23", "nist": "AC-6", "iso27001": ""}},
    {"id": str(uuid.uuid4()), "rule_id": "OS-010", "rule_name": "Container instance privileged execution", "severity": "CRITICAL", "resource_id": "/subscriptions/SUB/resourceGroups/rg/providers/Microsoft.ContainerInstance/containerGroups/aci-suspicious", "resource_type": "Microsoft.ContainerInstance/containerGroups", "resource_name": "aci-suspicious", "resource_group": "openshield-rg", "subscription_id": "YOUR_SUBSCRIPTION_ID", "region": "uksouth", "description": "Container runs with privileged context.", "remediation": "Remove privileged flag.", "detected_at": ts(0), "tool_version": "0.1.0", "compliance": {"cis": "CIS 5.2", "nist": "CM-7", "iso27001": ""}}
]

with open("scanner/output/test_findings.json", "w") as f:
    json.dump({"findings": findings}, f, indent=2)
print(f"Generated {len(findings)} test findings")
